import { readdir, mkdir, writeFile } from 'node:fs/promises';
const types=['question','failure','decision','surprise','requirement','drift'];
const records=[];
for(const type of types){
  let names=[];try{names=await readdir('.ai/ledger/'+type);}catch{}
  for(const name of names.filter(n=>n.endsWith('.md')).sort())records.push('- ['+type+': '+name.replace('.md','').replaceAll('-',' ')+']('+type+'/'+name+')');
}
await mkdir('.ai/ledger',{recursive:true});
await writeFile('.ai/ledger/index.md',[
  '# Ledger index','',
  'Generated by `node scripts/build-brief.mjs`. Do not edit by hand.',
  'Regenerate when a ledger record is added or changed.','',...records,'',
].join('\n'));
await writeFile('.ai/BRIEF.md',[
  '# Session brief','',
  'Generated by `node scripts/build-brief.mjs`. Do not edit by hand.',
  'Regenerate when the knowledge layer or ledger changes.','',
  'Bureau of other lives is a standalone Russian web and Android product pilot. Read the canonical sources before changing behaviour.','',
  '- [Product and acceptance](../docs/product.md)',
  '- [Requirements and sources](../docs/requirements.md)',
  '- [Decisions and reversal conditions](../docs/decisions.md)',
  '- [Architecture and storage limits](../docs/architecture.md)',
  '- [Runtime facts](../context/application.md)',
  '- [Verification and remaining limits](../docs/testing.md)',
  '- [Deployment and recovery](../docs/operations.md)',
  '- [Change provenance](../docs/changes.md)',
  '- [Android build, signing and recovery](../docs/android.md)',
  '- [Motivation and monetisation hypotheses](../docs/monetization.md)',
  '- [Ledger records](ledger/index.md)','',
].join('\n'));
