import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { MISSIONS, TRADITIONS, CATEGORIES } from '../public/data.mjs';
import { STORAGE_KEY, MAX_ENTRIES } from '../public/core.mjs';
import { CONTACTS_KEY, MAX_CONTACTS } from '../public/contacts.mjs';
import { FRONTEND_URL } from '../public/runtime-config.mjs';
import { MODULES, ASSETS } from './build-pages.mjs';
const app=await readFile('public/app.mjs','utf8');
const pkg=JSON.parse(await readFile('package.json','utf8'));
const views=[...(app.match(/const VIEWS = \{(.+)\};/)?.[1] || '').matchAll(/([a-z]+): \[/g)].map(match=>match[1]);
const content=[
  '# Application facts','',
  'Generated by `node scripts/extract-context.mjs`. Do not edit by hand.',
  'Regenerate when catalog, storage, views, package or build configuration changes.','',
  '- Canonical source: https://github.com/Tamagochigit/bureau-other-lives',
  '- Static frontend: '+FRONTEND_URL,
  '- Browser source: public; build: scripts/build-pages.mjs; output: out/pages',
  '- Published modules: '+MODULES.join(', '),
  '- Published non-module assets: index.html, .nojekyll, '+ASSETS.join(', '),
  '- Publication workflow: .github/workflows/pages.yml',
  '- Node engine: '+pkg.engines.node+'; CI: Node 24; package dependencies: '+Object.keys({...pkg.dependencies,...pkg.devDependencies}).length,
  '- Diary key: `'+STORAGE_KEY+'`; max entries: '+MAX_ENTRIES,
  '- Contact key: `'+CONTACTS_KEY+'`; max contacts: '+MAX_CONTACTS,
  '- Browser views: '+views.join(', '),
  '- Primary navigation: '+JSON.parse(app.match(/\['home','missions','friends','compass','diary'\]/)?.[0].replaceAll("'",'"') || '[]').join(', '),
  '- Home controls: '+[...app.slice(app.indexOf('function homePage()'),app.indexOf('function missionsPage()')).matchAll(/data-action="([^"]+)"/g)].map(match=>match[1]).join(', '),
  '- Home selectors: '+(app.includes('home-time') || app.includes('home-place') ? 'present' : 'none'),
  '- Missions: '+MISSIONS.length+'; traditions: '+TRADITIONS.length+'; categories: '+Object.keys(CATEGORIES).join(', '),
  '- Messaging: explicit HTTPS Telegram username/share links; no in-product message storage/API',
  '- Contacts are separate from diary backups; notes remain local.','',
].join('\n');
await mkdir('context',{recursive:true});
await writeFile('context/application.md',content);
