import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { MISSIONS, TRADITIONS, CATEGORIES } from '../dist/data.mjs';
import { STORAGE_KEY, MAX_ENTRIES } from '../dist/core.mjs';
const hosting=JSON.parse(await readFile('.openai/hosting.json','utf8'));
const app=await readFile('dist/app.mjs','utf8');
const homeDefaults=app.match(/const homeFilters = \{ time: '([^']+)', place: '([^']+)' \};/);
const views=[...(app.match(/const VIEWS = \{(.+)\};/)?.[1] || '').matchAll(/([a-z]+): \[/g)].map(m=>m[1]);
const content=[
  '# Application facts',
  '',
  'Generated by `node scripts/extract-context.mjs`. Do not edit by hand.',
  'Regenerate when application modules, catalog or hosting manifest change.',
  '',
  '- Site project: `'+hosting.project_id+'`',
  '- Static directory: `'+hosting.static.directory+'`',
  '- Storage key: `'+STORAGE_KEY+'`',
  '- Maximum entries: '+MAX_ENTRIES,
  '- Browser views: '+views.join(', '),
  '- Home selection defaults: time '+homeDefaults[1]+' minutes, place '+homeDefaults[2],
  '- Mission count: '+MISSIONS.length,
  '- Tradition count: '+TRADITIONS.length,
  '- Interest categories: '+Object.keys(CATEGORIES).join(', '),
  '- Runtime dependencies: none; browser ES modules.',
  '',
].join('\n');
await mkdir('context',{recursive:true});
await writeFile('context/application.md',content);
